// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package grpcserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Add user
type AddUserRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Interests            string   `protobuf:"bytes,6,opt,name=interests,proto3" json:"interests,omitempty"`
	FirstName            string   `protobuf:"bytes,7,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,8,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Age                  int32    `protobuf:"varint,9,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AddUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddUserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *AddUserRequest) GetInterests() string {
	if m != nil {
		return m.Interests
	}
	return ""
}

func (m *AddUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AddUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AddUserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

// User model
type User struct {
	UserId               int64                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	City                 string               `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Gender               string               `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Interests            string               `protobuf:"bytes,7,opt,name=interests,proto3" json:"interests,omitempty"`
	DateCreated          *timestamp.Timestamp `protobuf:"bytes,8,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	DateModify           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=date_modify,json=dateModify,proto3" json:"date_modify,omitempty"`
	FirstName            string               `protobuf:"bytes,10,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,11,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Age                  int32                `protobuf:"varint,12,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetInterests() string {
	if m != nil {
		return m.Interests
	}
	return ""
}

func (m *User) GetDateCreated() *timestamp.Timestamp {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

func (m *User) GetDateModify() *timestamp.Timestamp {
	if m != nil {
		return m.DateModify
	}
	return nil
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

// Update user request
type UpdateUserRequest struct {
	UserId               int64                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	City                 string               `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Gender               string               `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Interests            string               `protobuf:"bytes,7,opt,name=interests,proto3" json:"interests,omitempty"`
	DateCreated          *timestamp.Timestamp `protobuf:"bytes,8,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	DateModify           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=date_modify,json=dateModify,proto3" json:"date_modify,omitempty"`
	FirstName            string               `protobuf:"bytes,10,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,11,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Age                  int32                `protobuf:"varint,12,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UpdateUserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UpdateUserRequest) GetInterests() string {
	if m != nil {
		return m.Interests
	}
	return ""
}

func (m *UpdateUserRequest) GetDateCreated() *timestamp.Timestamp {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

func (m *UpdateUserRequest) GetDateModify() *timestamp.Timestamp {
	if m != nil {
		return m.DateModify
	}
	return nil
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type StatusResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *StatusResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type UserByIdRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByIdRequest) Reset()         { *m = UserByIdRequest{} }
func (m *UserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*UserByIdRequest) ProtoMessage()    {}
func (*UserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *UserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByIdRequest.Unmarshal(m, b)
}
func (m *UserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByIdRequest.Marshal(b, m, deterministic)
}
func (m *UserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByIdRequest.Merge(m, src)
}
func (m *UserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_UserByIdRequest.Size(m)
}
func (m *UserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByIdRequest proto.InternalMessageInfo

func (m *UserByIdRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserAddResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddResponse) Reset()         { *m = UserAddResponse{} }
func (m *UserAddResponse) String() string { return proto.CompactTextString(m) }
func (*UserAddResponse) ProtoMessage()    {}
func (*UserAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *UserAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddResponse.Unmarshal(m, b)
}
func (m *UserAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddResponse.Marshal(b, m, deterministic)
}
func (m *UserAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddResponse.Merge(m, src)
}
func (m *UserAddResponse) XXX_Size() int {
	return xxx_messageInfo_UserAddResponse.Size(m)
}
func (m *UserAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddResponse proto.InternalMessageInfo

func (m *UserAddResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UserAddResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UserAddResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// Get User By Login
type UserByLoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByLoginRequest) Reset()         { *m = UserByLoginRequest{} }
func (m *UserByLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserByLoginRequest) ProtoMessage()    {}
func (*UserByLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *UserByLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByLoginRequest.Unmarshal(m, b)
}
func (m *UserByLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserByLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByLoginRequest.Merge(m, src)
}
func (m *UserByLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserByLoginRequest.Size(m)
}
func (m *UserByLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByLoginRequest proto.InternalMessageInfo

func (m *UserByLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

// Set Password
type SetPasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SetPasswordRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// Add User Role
type UserRole struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId               int64    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRole) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

// Check Auth
type CheckAuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthRequest) Reset()         { *m = CheckAuthRequest{} }
func (m *CheckAuthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAuthRequest) ProtoMessage()    {}
func (*CheckAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *CheckAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthRequest.Unmarshal(m, b)
}
func (m *CheckAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthRequest.Marshal(b, m, deterministic)
}
func (m *CheckAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthRequest.Merge(m, src)
}
func (m *CheckAuthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAuthRequest.Size(m)
}
func (m *CheckAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthRequest proto.InternalMessageInfo

func (m *CheckAuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CheckAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// User response
type UserResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Date                 *User    `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UserResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UserResponse) GetDate() *User {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "api.AddUserRequest")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*UpdateUserRequest)(nil), "api.UpdateUserRequest")
	proto.RegisterType((*StatusResponse)(nil), "api.StatusResponse")
	proto.RegisterType((*UserByIdRequest)(nil), "api.UserByIdRequest")
	proto.RegisterType((*UserAddResponse)(nil), "api.UserAddResponse")
	proto.RegisterType((*UserByLoginRequest)(nil), "api.UserByLoginRequest")
	proto.RegisterType((*SetPasswordRequest)(nil), "api.SetPasswordRequest")
	proto.RegisterType((*UserRole)(nil), "api.UserRole")
	proto.RegisterType((*CheckAuthRequest)(nil), "api.CheckAuthRequest")
	proto.RegisterType((*UserResponse)(nil), "api.UserResponse")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x56, 0xbe, 0x93, 0x49, 0xdf, 0xbc, 0xed, 0x36, 0x24, 0xc6, 0x6d, 0x45, 0xf1, 0xa9, 0x8a,
	0x44, 0x2c, 0xc2, 0xad, 0x80, 0x44, 0x3f, 0x24, 0x14, 0x04, 0xa8, 0x72, 0xa9, 0x84, 0x2a, 0x41,
	0xe4, 0xc6, 0xd3, 0xd4, 0xc2, 0xb1, 0x8d, 0x77, 0x53, 0x54, 0x21, 0x2e, 0x9c, 0xb8, 0xf3, 0xd3,
	0xf8, 0x0b, 0x1c, 0x39, 0x70, 0xe7, 0x82, 0x76, 0xd6, 0x6e, 0x9c, 0xe0, 0x14, 0xe8, 0x99, 0x9b,
	0xe7, 0xeb, 0xf1, 0xec, 0x33, 0xcf, 0xce, 0xc2, 0x7f, 0x76, 0xe8, 0x9a, 0x76, 0xe8, 0x76, 0xc3,
	0x28, 0x10, 0x01, 0x2b, 0xd8, 0xa1, 0xab, 0xaf, 0x8f, 0x82, 0x60, 0xe4, 0xa1, 0x49, 0x21, 0xdf,
	0x0f, 0x84, 0x2d, 0xdc, 0xc0, 0xe7, 0x2a, 0x45, 0xbf, 0x15, 0x47, 0xc9, 0x3a, 0x99, 0x9c, 0x9a,
	0xc2, 0x1d, 0x23, 0x17, 0xf6, 0x38, 0x54, 0x09, 0xc6, 0xf7, 0x1c, 0x34, 0x76, 0x1c, 0xe7, 0x88,
	0x63, 0x64, 0xe1, 0xdb, 0x09, 0x72, 0xc1, 0x9a, 0x50, 0xf2, 0x82, 0x91, 0xeb, 0x6b, 0xb9, 0xcd,
	0xdc, 0x56, 0xcd, 0x52, 0x06, 0xd3, 0xa1, 0x1a, 0xda, 0x9c, 0xbf, 0x0b, 0x22, 0x47, 0xcb, 0x53,
	0xe0, 0xd2, 0x96, 0x15, 0x38, 0xb6, 0x5d, 0x4f, 0x2b, 0xa8, 0x0a, 0x32, 0x18, 0x83, 0xe2, 0xd0,
	0x15, 0x17, 0x5a, 0x91, 0x9c, 0xf4, 0xcd, 0x5a, 0x50, 0x1e, 0xa1, 0xef, 0x60, 0xa4, 0x95, 0xc8,
	0x1b, 0x5b, 0x6c, 0x1d, 0x6a, 0xae, 0x2f, 0x30, 0x42, 0x2e, 0xb8, 0x56, 0xa6, 0xd0, 0xd4, 0xc1,
	0x36, 0x00, 0x4e, 0xdd, 0x88, 0x8b, 0x81, 0x6f, 0x8f, 0x51, 0xab, 0xa8, 0x30, 0x79, 0x9e, 0xdb,
	0x63, 0x64, 0x6b, 0x50, 0xf3, 0xec, 0x24, 0x5a, 0x55, 0xbd, 0x49, 0x07, 0x05, 0x97, 0xa1, 0x60,
	0x8f, 0x50, 0xab, 0x6d, 0xe6, 0xb6, 0x4a, 0x96, 0xfc, 0x34, 0x7e, 0xe4, 0xa1, 0x28, 0xcf, 0xcb,
	0xda, 0x50, 0x99, 0x70, 0x8c, 0x06, 0xae, 0x43, 0x47, 0x2d, 0x58, 0x65, 0x69, 0xf6, 0x9d, 0x29,
	0x03, 0xf9, 0x45, 0x0c, 0x14, 0x16, 0x31, 0x50, 0xcc, 0x62, 0xa0, 0x94, 0xc9, 0x40, 0x79, 0x31,
	0x03, 0x95, 0x79, 0x06, 0x1e, 0xc2, 0x92, 0x63, 0x0b, 0x1c, 0x0c, 0x23, 0xb4, 0x05, 0x3a, 0x74,
	0xca, 0x7a, 0x4f, 0xef, 0xaa, 0xf1, 0x76, 0x93, 0xf1, 0x76, 0x5f, 0x24, 0xe3, 0xb5, 0xea, 0x32,
	0x7f, 0x4f, 0xa5, 0xb3, 0xfb, 0x40, 0xe6, 0x60, 0x1c, 0x38, 0xee, 0xe9, 0x05, 0x91, 0x71, 0x75,
	0x35, 0xc8, 0xf4, 0x67, 0x94, 0x3d, 0xc7, 0x3e, 0x5c, 0xc9, 0x7e, 0x3d, 0x9b, 0xfd, 0xa5, 0x29,
	0xfb, 0xdf, 0xf2, 0xb0, 0x72, 0x14, 0x4a, 0xf8, 0xb4, 0xe6, 0xfe, 0x72, 0x14, 0xff, 0xe8, 0xfe,
	0x53, 0xba, 0x1f, 0x41, 0xe3, 0x50, 0xd8, 0x62, 0xc2, 0x2d, 0xe4, 0x61, 0xe0, 0x73, 0x94, 0x8c,
	0x70, 0xf2, 0x10, 0xd3, 0x55, 0x2b, 0xb6, 0xa4, 0xdf, 0x41, 0x21, 0x49, 0x55, 0x54, 0xc7, 0x96,
	0xd1, 0x81, 0xff, 0xe5, 0xa4, 0x76, 0x2f, 0xfa, 0xce, 0xef, 0xa6, 0x65, 0x1c, 0xab, 0xdc, 0x1d,
	0xc7, 0xb9, 0xee, 0xef, 0xd2, 0xd8, 0x85, 0x19, 0xec, 0x0e, 0x30, 0xd5, 0xc7, 0x53, 0x29, 0x81,
	0x2b, 0x97, 0x95, 0xd1, 0x07, 0x76, 0x88, 0xe2, 0x20, 0xbe, 0x9d, 0x49, 0x6e, 0xfa, 0x02, 0xe7,
	0xe6, 0x2e, 0x70, 0xea, 0xb7, 0xf9, 0x99, 0xdf, 0x3e, 0x80, 0x2a, 0x09, 0x35, 0xf0, 0x70, 0xb1,
	0x4a, 0xdb, 0x50, 0x89, 0x02, 0x0f, 0x53, 0xd5, 0xd2, 0xec, 0x3b, 0xc6, 0x3e, 0x2c, 0xef, 0x9d,
	0xe1, 0xf0, 0xcd, 0xce, 0x44, 0x9c, 0x5d, 0x7b, 0xbf, 0x1a, 0xaf, 0x60, 0x49, 0x5d, 0x96, 0x6b,
	0x72, 0xba, 0x01, 0x45, 0x29, 0x30, 0x22, 0xb4, 0xde, 0xab, 0x75, 0xe5, 0x13, 0x42, 0x80, 0xe4,
	0xee, 0x7d, 0x2a, 0x42, 0x49, 0x9a, 0x9c, 0x3d, 0x81, 0x4a, 0xfc, 0x18, 0xb0, 0x55, 0xca, 0x9a,
	0x7d, 0x1a, 0xf4, 0xe6, 0x65, 0x69, 0x6a, 0xc4, 0x46, 0xf3, 0xe3, 0x97, 0xaf, 0x9f, 0xf3, 0x0d,
	0xa3, 0x66, 0x9e, 0xdf, 0x35, 0x25, 0x23, 0x7c, 0x3b, 0xd7, 0x61, 0x16, 0xd4, 0x1f, 0xa3, 0x48,
	0xa4, 0xc3, 0xa6, 0xa5, 0x29, 0x25, 0xe9, 0x2b, 0xd3, 0x5e, 0x12, 0x34, 0x9d, 0xd0, 0x9a, 0x8c,
	0x25, 0x68, 0xe6, 0xfb, 0x98, 0xf4, 0x0f, 0xec, 0x25, 0xc0, 0x74, 0x77, 0xb0, 0x96, 0x2a, 0x9e,
	0x5f, 0x26, 0xba, 0x6a, 0x7d, 0x56, 0xf6, 0xc6, 0x06, 0xc1, 0xb6, 0xf5, 0x0c, 0x58, 0xd9, 0xed,
	0x21, 0xc0, 0x3e, 0x7a, 0x18, 0x23, 0x67, 0x37, 0x9b, 0x89, 0x1b, 0xb7, 0xdb, 0xc9, 0x6a, 0xf7,
	0x35, 0xd4, 0x53, 0x32, 0x64, 0x6d, 0x55, 0xff, 0x8b, 0x30, 0xb3, 0x81, 0x6f, 0x13, 0xf0, 0x5a,
	0xaf, 0x25, 0x81, 0x13, 0x29, 0xcc, 0x36, 0x7d, 0x00, 0xb5, 0x4b, 0x75, 0xb1, 0x1b, 0x04, 0x32,
	0xaf, 0xb6, 0x2c, 0x86, 0x6f, 0x12, 0xf2, 0xaa, 0xd1, 0x90, 0xc8, 0x43, 0x59, 0x70, 0x47, 0xa2,
	0x6e, 0xe7, 0x3a, 0xbb, 0xad, 0xe3, 0xa6, 0x49, 0x6b, 0xd0, 0xb7, 0x3d, 0x73, 0x14, 0x85, 0x43,
	0x8e, 0xd1, 0x39, 0x46, 0x27, 0x65, 0x5a, 0x5a, 0xf7, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x54,
	0xb3, 0x97, 0xd2, 0x82, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	// Add new user
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*UserAddResponse, error)
	// Ger user by id
	GetUserById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Update user
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Delete user by id
	DeleteUser(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Set password for new user
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Check credential of an user
	CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*UserAddResponse, error) {
	out := new(UserAddResponse)
	err := c.cc.Invoke(ctx, "/api.Users/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/api.Users/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/api.Users/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUser(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/api.Users/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/api.Users/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/api.Users/CheckAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	// Add new user
	AddUser(context.Context, *AddUserRequest) (*UserAddResponse, error)
	// Ger user by id
	GetUserById(context.Context, *UserByIdRequest) (*UserResponse, error)
	// Update user
	UpdateUser(context.Context, *UpdateUserRequest) (*StatusResponse, error)
	// Delete user by id
	DeleteUser(context.Context, *UserByIdRequest) (*StatusResponse, error)
	// Set password for new user
	SetPassword(context.Context, *SetPasswordRequest) (*StatusResponse, error)
	// Check credential of an user
	CheckAuth(context.Context, *CheckAuthRequest) (*UserResponse, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) AddUser(ctx context.Context, req *AddUserRequest) (*UserAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUsersServer) GetUserById(ctx context.Context, req *UserByIdRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedUsersServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUsersServer) DeleteUser(ctx context.Context, req *UserByIdRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUsersServer) SetPassword(ctx context.Context, req *SetPasswordRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (*UnimplementedUsersServer) CheckAuth(ctx context.Context, req *CheckAuthRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuth not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Users/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Users/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserById(ctx, req.(*UserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Users/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Users/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUser(ctx, req.(*UserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Users/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Users/CheckAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CheckAuth(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Users_AddUser_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _Users_GetUserById_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Users_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Users_DeleteUser_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _Users_SetPassword_Handler,
		},
		{
			MethodName: "CheckAuth",
			Handler:    _Users_CheckAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
