version: '3'
services:
  master:
    image: mysql:5.7.27
    environment:
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - net
    volumes:
      - ./mysql-conf/master/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql-conf/master/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  unit_tests:
    build:
      context: ./social
      dockerfile: Dockerfile.full
    environment:
      APP_BUILD: prod

      MASTER_PASSWORD: qwerty
      MASTER_USER: soc_user
      MASTER_DATABASE: soc_db
      MASTER_PORT: 3306
      MASTER_HOST: master

    command: "true"
    restart: on-failure
    networks:
      - net

networks:
  net:
    driver: bridge
