version: '3'
services:

  db:
    image: mysql:5.7.27
    environment:
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - ./social/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  grpc.ru:
    build: ./social
    environment:
      GRPC_PORT: 50051
      GRPC_HOST: 0.0.0.0
      HTTP_PORT: 8080
      HTTP_HOST: 0.0.0.0
      APP_BUILD: prod
      MYSQL_PASSWORD: qwerty
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
      MYSQL_PORT: 3306
      MYSQL_HOST: db
    command: sh -c './wait-for.sh db:3306 -- ./main -s rpc'
    restart: on-failure
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - net

  rest.ru:
    build: ./social
    environment:
      GRPC_PORT: 50051
      GRPC_HOST: grpc.ru
      HTTP_PORT: 80
      HTTP_HOST: 0.0.0.0
      APP_BUILD: prod
      MYSQL_PASSWORD: qwerty
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
      MYSQL_PORT: 3306
      MYSQL_HOST: db
    command:  sh -c './wait-for.sh grpc.ru:50051 -- ./main -s web'
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net

volumes:
  tmp:

networks:
  net:
    driver: bridge
