version: '3'
services:

  db:
    image: mysql:5.7.27
    container_name: master
    environment:
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.conf/master/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql.conf/master/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  slave:
    image: mysql:5.7.27
    container_name: slave
    environment:
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - net
    ports:
      - "3307:3306"
    volumes:
      - ./mysql.conf/slave/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql.conf/slave/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  rest.ru:
    image: social:1.1
    container_name: web
    environment:
      GRPC_PORT: 50051
      GRPC_HOST: grpc.ru
      HTTP_PORT: 8080
      HTTP_HOST: 0.0.0.0
      APP_BUILD: dev
      MYSQL_PASSWORD: qwerty
      MYSQL_USER: soc_user
      MYSQL_DATABASE: soc_db
      MYSQL_PORT: 3306
      MYSQL_HOST: db
      SESSION_KEY: Auth
      SESSION_TIME: 24
    command:  go run main.go -s web
    restart: on-failure
    volumes:
      - ./social/:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net
volumes:
  tmp:
networks:
  net:
    driver: bridge


