/*
 * api/api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiUpdateUserRequest struct {
	UserId int64 `json:"user_id"`

	Login string `json:"login"`

	Email string `json:"email"`

	IsActive bool `json:"is_active,omitempty"`

	IsStaff bool `json:"is_staff,omitempty"`

	DateCreated time.Time `json:"date_created,omitempty"`

	DateModify time.Time `json:"date_modify,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`
}
