/*
 * api/api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiUserResponse struct {
	Status bool `json:"status"`

	Detail string `json:"detail,omitempty"`

	Date *ApiUser `json:"date,omitempty"`
}
