/*
 * api/api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiUserRole struct {
	UserId int64 `json:"user_id"`

	RoleId int64 `json:"role_id"`
}
