/*
 * api/api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiAddUserRequest struct {
	Login string `json:"login"`

	Password string `json:"password"`

	Email string `json:"email"`

	IsActive bool `json:"is_active,omitempty"`

	IsStaff bool `json:"is_staff,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`
}
