/*
 * api/api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiRole struct {
	Id int64 `json:"id"`

	Name string `json:"name"`

	Title string `json:"title,omitempty"`
}
