CHANGE MASTER TO MASTER_HOST = 'master', MASTER_PORT = 3306,  MASTER_USER = 'slave_user', MASTER_PASSWORD = 'qwerty', MASTER_AUTO_POSITION = 1;
START SLAVE;
INSTALL PLUGIN rpl_semi_sync_slave SONAME 'semisync_slave.so';
STOP SLAVE IO_THREAD;
START SLAVE IO_THREAD;