/*
 * nn-invest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package webserver

import (
	"net/http"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

func (s *HttpServer) Routing() []Route {
	return []Route{

		{
			"login",
			"GET",
			"/login",
			s.loginForm,
		},
		{
			"registration",
			"GET",
			"/registration",
			s.registrationForm,
		},
		{
			"profile",
			"GET",
			"/profile/{user_id}",
			s.userProfile,
		},
		{
			"index",
			"GET",
			"/",
			s.Index,
		},
		{
			"logout",
			"GET",
			"/logout",
			s.logOut,
		},
		{
			"login_handler",
			"POST",
			"/handler/login",
			s.loginHandler,
		},
		{
			"registration_handler",
			"POST",
			"/handler/registration",
			s.registrationHandler,
		},
	}
}
